"""04_added_user_relations

Revision ID: 538acd978763
Revises: de35544fa845
Create Date: 2023-03-16 00:13:02.112588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538acd978763'
down_revision = 'de35544fa845'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
