"""05_del_unique_property

Revision ID: 947ec694e83d
Revises: 538acd978763
Create Date: 2023-03-17 00:59:33.316785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947ec694e83d'
down_revision = '538acd978763'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('short_link_original_url_key', 'short_link', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('short_link_original_url_key', 'short_link', ['original_url'])
    # ### end Alembic commands ###
