"""03_add_access_log_model

Revision ID: de35544fa845
Revises: 58d876a05253
Create Date: 2023-03-15 23:40:52.222921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de35544fa845'
down_revision = '58d876a05253'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_link_id', sa.Integer(), nullable=False),
    sa.Column('connection_info', sa.Text(), nullable=True),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['short_link_id'], ['short_link.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_log')
    # ### end Alembic commands ###
